version: 2.1

executors:
  node_latest:
    docker:
    - image: circleci/node:latest
  node_lts:
    docker:
      - image: circleci/node:lts
  default_executor: node_latest

aliases:
  - &defaults
    working_directory: ~/verdaccio
  - &ignore_non_dev_branches
    filters:
      tags:
        only: /.*/
      branches:
        ignore:
          - /release\/.*/
  - &filter-only-master
   branches:
     only:
       - master
jobs:
  prepare:
    <<: *defaults
    executor: default_executor
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: npm -g install pnpm@next
      - run:
          name: Install dependencies
          command: |
            cd website
            pnpm install
  test_build_website:
    executor: default_executor
    steps:
      - run:
          name: build website
          command: pnpm run build

  deploy-website:
    <<: *defaults
    executor: default_executor
    steps:
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "verdacciobot@users.noreply.github.com"
            git config --global user.name "Verdaccio bot for Deployments"
            echo "machine github.com login verdacciobot password $GITHUB_TOKEN" > ~/.netrc
            GIT_USER=verdacciobot USE_SSH=false pnpm run publish-gh-pages
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - prepare:
        <<: *ignore_non_dev_branches
      - test_build_website:
         requires:
            - prepare
      - deploy-website:
         requires:
            - prepare
         filters: *filter-only-master