version: 2

aliases:
  - &defaults
    working_directory: ~/verdaccio
  - &filter-only-master
   branches:
     only:
       - master
jobs:
  build:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - run:
          name: build
          command: |
            cd website
            yarn install
            GIT_USER=verdacciobot USE_SSH=false yarn run build
  deploy-website:
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "verdacciobot@users.noreply.github.com"
            git config --global user.name "Verdaccio bot for Deployments"
            echo "machine github.com login verdacciobot password $GITHUB_TOKEN" > ~/.netrc
            cd website
            yarn install
            GIT_USER=verdacciobot USE_SSH=false yarn run publish-gh-pages
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
      - deploy-website:
         filters: *filter-only-master