version: 2

aliases:
  - &defaults
    working_directory: ~/verdaccio
  - &filter-only-master
   branches:
     only:
       - master
jobs:
  deploy-website:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: npm -g install pnpm@next
      - run:
          name: Test build
          command: |
            cd website
            pnpm install
            pnpm run build
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "verdacciobot@users.noreply.github.com"
            git config --global user.name "Verdaccio bot for Deployments"
            echo "machine github.com login verdacciobot password $GITHUB_TOKEN" > ~/.netrc
            cd website
            pnpm install
            GIT_USER=verdacciobot USE_SSH=false pnpm run publish-gh-pages
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
         filters: *filter-only-master